build_from:
  aarch64: ghcr.io/sysadminsmedia/homebox:latest
  amd64: ghcr.io/sysadminsmedia/homebox:latest
  armhf: ghcr.io/sysadminsmedia/homebox:latest
  armv7: ghcr.io/sysadminsmedia/homebox:latest
