build_from:
  aarch64: ghcr.io/manyfold3d/manyfold-solo:latest
  amd64: ghcr.io/manyfold3d/manyfold-solo:latest
  armhf: ghcr.io/manyfold3d/manyfold-solo:latest
  armv7: ghcr.io/manyfold3d/manyfold-solo:latest
